name: Run FinLab Test

on:
  workflow_dispatch: # 讓網頁出現「執行」按鈕

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run test
        env:
          FINLAB_TOKEN: ${{ secrets.FINLAB_TOKEN }}
        run: python main.py
